name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python for YAML Linting YAML
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Lint YAML
        run: |
          cd modules/validate-schema
          pip install -r requirements.txt
          ./validate.py ../../models.yaml ../models-schema.yaml

  release:
    needs: validate
    runs-on: ubuntu-24.04
    outputs:
      released: ${{ steps.release-please.outputs.release_created }}
      tag: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

  update-model:
    needs: release
    if: ${{ needs.release.outputs.released }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update models.yaml
        run: |
          VERSION="${{ needs.release.outputs.tag }}"
          DATE=$(date +'%Y-%m-%d')
          sed -i.bak -E \
            -e "s/^version: .*/version: ${VERSION#v}/" \
            -e "s/^updated: .*/updated: ${DATE}/" models.yaml
          rm models.yaml.bak
      - name: Commit updated models.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "chore: update models.yaml for release ${{ needs.release.outputs.tag }}"
          git push origin main
      - name: Attach updated models.yaml to Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ needs.release.outputs.tag }}" models.yaml --clobber
  update-node-module:
    needs: release
    if: ${{ needs.release.outputs.released }}
    runs-on: ubuntu-24.04
    steps:
      - name: Update Node Package Version
        run: |
          cd modules/node
          npm version "${{ needs.release.outputs.tag }}" --no-git-tag-version
          git add package.json
          git commit -m "chore: update node package version for release ${{ needs.release.outputs.tag }}"
          git push origin main
