name: "Model Integration Tests"

# This workflow runs only when manually triggered with input parameters
on:
  workflow_dispatch:
    inputs:
      openai_api_key:
        description: 'OpenAI API Key'
        required: true
        type: string
      base_url:
        description: 'Custom OpenAI API base URL (optional)'
        required: false
        type: string

# Basic read permissions are sufficient
permissions:
  contents: read

jobs:
  integration-test:
    name: Run Model Integration Tests
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./modules/integration-tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: make init

      - name: Run Integration Tests
        run: make integration-test
        env:
          OPENAI_API_KEY: ${{ inputs.openai_api_key }}
          OPENAI_BASE_URL: ${{ inputs.base_url }}
