name: "CI/CD: Python Module"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  PYTHON_VERSION: "3.10"

jobs:
  validate:
    name: Validate
    defaults:
      run:
        working-directory: ./modules/python
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint Code
        run: make lint

      - name: Build Package
        run: make build

      - name: Test with Coverage
        run: make test

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./artifacts/

  upload-coverage:
    name: Upload Coverage
    needs: validate
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./modules/python
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./artifacts

      # # Upload the first coverage report
      # - name: Upload Coverage Report 1
      #   uses: codecov/codecov-action@v5
      #   with:
      #     directory: ./artifacts/coverage/report1
      #     token: ${{ secrets.CODECOV_TOKEN }}
